node-1:
  ansible_ssh_host: node-1.example.com
  tags:
    - development
    - node
  hostvars:
    attr_1: value1
    attr_2:
      - value2
      - value3
    attr_3:
      something: value4

node-2:
  ansible_ssh_host: node-2.example.com
  tags:
    - production
    - node
  hostvars:
    attr_1: value1
    attr_2:
      - value2
      - value3
    attr_3:
      something: value4

proxy-1:
  ansible_ssh_host: proxy-1.example.com
  tags:
    - development
    - proxy
    - apache

proxy-2:
  ansible_ssh_host: proxy-2.example.com
  tags:
    - production
    - proxy
    - apache