---
- name: prepare the db server
  hosts: rhel_nodes
  gather_facts: no
  become: yes
  remote_user: ansible

  tasks:
    - name: ensure db server is up to date
      yum:
        name: mariadb-server
        state: latest
      register: output
      ignore_errors: yes 
      ignore_unreachable: true
   
    - name: print output
      debug:
        var: output