---
- name: mark task as failed based on some condition
  hosts: rhel_nodes
  gather_facts: no

  tasks:
    - name: run a task that always passes
      shell: "cat /proc/meminfo|grep -i memtotal|awk '{print $2/1024/1024}'"
      register: output

    - name: print task output
      debug:
        var: output.stdout
        
    - name: report task failure with a message
      fail:
        msg: "Insufficient memory"
      when: "output.stdout|float < 4"