---
- name: force handlers when some tasks fail
  hosts: rhel_nodes
  gather_facts: no
  become: true
  force_handlers: yes

  tasks:
    - name: task that always notifies
      command: /bin/true
      notify:
        restart db

    - name: task that fails
      yum:
        name: notapkg
        state: latest
      #ignore_errors: yes

  handlers:
    - name: restart db
      service:
        name: mariadb
        state: restarted