- name: test play
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: print some output
      debug:
        msg: 
          - yaml playbook without start and end delimiters
          - "{{ hostvars[inventory_hostname] }}"
