---
- name: get local facts stored in /etc/ansible/facts.d/custom.fact
  hosts: linux_nodes
  gather_facts: no

  tasks:
    - name: manually gather facts
      setup:

    - name: print local facts
      debug:
        msg: 
          - "{{ansible_facts.ansible_local.custom.general.package}}"
          #- "{{ansible_facts.ansible_local.custom}}"
          #- "{{ansible_facts.ansible_local.custom.packages}}"
          #- "{{ansible_facts.ansible_local.custom.users}}"
          #- "{{ansible_facts.ansible_local.custom.packages['web-server']}}"
          #- "{{ansible_facts.ansible_local.custom.users['user2']}}"
