---
- name: /etc/hosts is up to date
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: print facts
      debug:
        var: ansible_hostname, inventory_hostname 
        #var: ansible_facts['default_ipv4']['address'], ansible_facts['fqdn'], ansible_facts['hostname']

    - name: Deploy /etc/hosts
      template:
        src: templates/hosts_content.j2
        dest: /home/{{ ansible_user_id }}/files/hosts