---
- name: play to demonstarte rolling update using serial keyword
  hosts: all
  gather_facts: no
  become: true
  # serial: 3

  tasks:
    - name: ensure maria db is up to date
      package:
        name: mariadb-server
        state: latest
      notify: restart db

  handlers:
    - name: restart db
      service:
        name: mariadb
        state: restarted